### ISSUE TITLE
服务器搭建失败

### ISSUE THREAD

**Issue by RozaliyaOlenyeva** [chenyongzhe/MyQQ#1]
我按照您说的修改了dbcpconfig.properties 配置文件
但是客户端Client()仍然无法正常启动 显示如下信息：
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:493)
	at java.base/sun.nio.ch.Net.connect(Net.java:482)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339)
	at java.base/java.net.Socket.connect(Socket.java:603)
	at java.base/java.net.Socket.connect(Socket.java:552)
	at java.base/java.net.Socket.<init>(Socket.java:475)
	at java.base/java.net.Socket.<init>(Socket.java:249)
	at test.Client.main(Client.java:16)

Process finished with exit code 0
求解

**Comment by chenyongzhe** [comment]
你先确认一下app登录时登录页面的ip地址是不是你服务器ip,然后确认你的安卓手机或者安卓虚拟机和你的服务器能不能ping 通。

**Comment by RozaliyaOlenyeva** [comment]
万分感谢，您的帮助对我很重要，现在它能够正常运作了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenyongzhe/MyQQ"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月20日(星期天) 晚上10:53
收件人:&nbsp;"chenyongzhe/MyQQ"<MyQQ@noreply.github.com&gt;;
抄送:&nbsp;"hhh"<1821566657@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chenyongzhe/MyQQ] 服务器搭建失败 (#1)





 
你先确认一下app登录时登录页面的ip地址是不是你服务器ip,然后确认你的安卓手机或者安卓虚拟机和你的服务器能不能ping 通。
